import { Vehicle } from '@/types'

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    type: 'sedan',
    price: 89,
    location: 'San Francisco, CA',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
    ],
    description: 'Premium electric sedan with autopilot features. Perfect for city driving and long trips.',
    features: ['Autopilot', 'All-wheel drive', 'Premium interior', 'Supercharging'],
    available: true,
    ownerId: 'owner1',
    ownerName: 'John Doe',
    rating: 4.8,
    reviewCount: 127,
    mileage: 5000,
    fuelType: 'electric',
    transmission: 'automatic',
    seats: 5,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2022,
    type: 'suv',
    price: 120,
    location: 'Los Angeles, CA',
    images: [
      'https://images.unsplash.com/photo-1507136566002-c504d9af63e4?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    description: 'Rugged off-road SUV perfect for adventures. Convertible top for open-air driving.',
    features: ['4x4', 'Convertible top', 'Off-road tires', 'Premium sound system'],
    available: true,
    ownerId: 'owner2',
    ownerName: 'Jane Smith',
    rating: 4.6,
    reviewCount: 89,
    mileage: 15000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 5,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    make: 'BMW',
    model: 'X5',
    year: 2023,
    type: 'luxury',
    price: 199,
    location: 'New York, NY',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    ],
    description: 'Luxury SUV with premium features and exceptional comfort. Perfect for business or leisure.',
    features: ['Leather seats', 'Panoramic roof', 'Premium sound', 'All-wheel drive'],
    available: true,
    ownerId: 'owner3',
    ownerName: 'Mike Johnson',
    rating: 4.9,
    reviewCount: 203,
    mileage: 8000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 7,
    createdAt: '2024-01-08',
  },
  {
    id: '4',
    make: 'Ford',
    model: 'F-150',
    year: 2022,
    type: 'truck',
    price: 110,
    location: 'Austin, TX',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800',
    ],
    description: 'Powerful pickup truck with excellent towing capacity. Great for work or weekend projects.',
    features: ['4x4', 'Towing package', 'Bed liner', 'Backup camera'],
    available: true,
    ownerId: 'owner4',
    ownerName: 'Sarah Williams',
    rating: 4.7,
    reviewCount: 156,
    mileage: 22000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 5,
    createdAt: '2024-01-05',
  },
  {
    id: '5',
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    type: 'sedan',
    price: 65,
    location: 'Seattle, WA',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    ],
    description: 'Reliable and fuel-efficient sedan perfect for daily commuting and city driving.',
    features: ['Fuel efficient', 'Apple CarPlay', 'Safety features', 'Comfortable seats'],
    available: true,
    ownerId: 'owner5',
    ownerName: 'David Brown',
    rating: 4.5,
    reviewCount: 94,
    mileage: 12000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 5,
    createdAt: '2024-01-12',
  },
  {
    id: '6',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2023,
    type: 'luxury',
    price: 299,
    location: 'Miami, FL',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
    ],
    description: 'Ultra-luxury sedan with cutting-edge technology and unmatched comfort.',
    features: ['Massage seats', 'Burmester audio', 'Magic Body Control', 'MBUX'],
    available: true,
    ownerId: 'owner6',
    ownerName: 'Emily Davis',
    rating: 5.0,
    reviewCount: 45,
    mileage: 3000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    seats: 5,
    createdAt: '2024-01-18',
  },
]

